### ISSUE TITLE
Filament voltage should be DC for this display

### ISSUE THREAD

**Issue by robjen** [qrti/VFD-HCS-12SS59T#1]
Thanks for the code and circuit examples, good job.

FYI here is a data sheet for this display please feel free to add to repository 

Filament voltage is DC so no need to go to trouble of generating AC supply, so theses are even simpler to use!
[16_seg_HCS-12SS59T.PDF](https://github.com/qrti/VFD-HCS-12SS59T/files/1967171/16_seg_HCS-12SS59T.PDF)

**Comment by qrti** [comment]
Some people expressed concern that AC supply of filaments will reduce their lifespan
[http://www.tlt.co.jp/tlt/english/products/industrial_light/miniature_lamp/catalog/info.htm](http://www.tlt.co.jp/tlt/english/products/industrial_light/miniature_lamp/catalog/info.htm) 
and search for 'Notching'

But you are right, the display works well with DC supply.
