### ISSUE TITLE
OSC Values

### ISSUE THREAD

**Issue by MarkOude** [qrti/VFD-HCS-12SS59T#2]
Hello!

I am an German, and I bought 2 of these Displays.
I do not own an 8.2 picoFarad capacitor and 8,2 kOhms

Is there an form to calculate some other values?

Or are there other values for capacitors and Resistors?

Thanks in advance!

Sorry for my (bad) english

**Comment by qrti** [comment]
Hallo Mark,

keine Ahnung wie genau diese Werte eingehalten werden müssen. Der 
RC-Schwingkreis bestimmt die Taktfrequenz des Displays, also auch die 
der SPI Übertragung, möglich dass das Display bei zu großen Abweichungen 
nicht mehr funktioniert. Vermutlich sind also nicht mehr als die +- 10 % 
der Bauteil Toleranz drin. Über gleichwertige RC-Kombinationen habe ich 
leider keine Informationen.


Viele Grüße
Kurt



-- 

mail
mailto:qrt@qland.de

home
http://www.qland.de

youtube
http://www.youtube.com/user/qrti

github
https://github.com/qrti
