### ISSUE TITLE
Can i use the oscilator from the 'AC filament supply' to power the 'combined clock supply'?

### ISSUE THREAD

**Issue by sebastius** [qrti/VFD-HCS-12SS59T#4]
I want to do my clock in hardware, as i'll be using an ESP32 as microcontroller and timing is... finnicky on these chips. So i'd like to combine the two schematics by using the 74132 oscillator (can you use any 74132 chip or 4093 perhaps?) to power up both the AC filament supply and the high voltage driver?

Also, VCC: is this schematic only working on 5v or can 3.3v also be used?

**Comment by qrti** [comment]
74HC132 and 74HCT132 produce different timing, the 74 standard and LS types or a 4093 might even not oscillate properly with the given RC values
Vcc 3.3 V might be too low for the charge pump, additional stages will reduce the available current
you have to try yourself in both cases
